name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint (Strict)
      run: |
        swiftlint --strict --reporter github-actions-logging
        
    - name: Run SwiftLint (Warnings Only)
      if: failure()
      run: |
        swiftlint --reporter github-actions-logging
        
  swift-format:
    name: Swift Format Check
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install swift-format
      run: |
        brew install swift-format
        
    - name: Check Swift Format
      run: |
        swift-format lint --recursive Sources Tests
        
  dependency-review:
    name: Dependency Review
    runs-on: macos-14
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      
  security-scan:
    name: Security Scan
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Semgrep
      run: |
        brew install semgrep
        
    - name: Run Semgrep Security Scan
      run: |
        # Run Semgrep with Swift and security rules
        semgrep --config=p/swift --config=p/security-audit --config=p/secrets . || echo "Semgrep scan completed with findings"
        
    - name: Check for hardcoded secrets
      run: |
        # Simple regex patterns for common secrets
        echo "Checking for potential secrets..."
        
        # API keys (case-insensitive)
        if grep -ri "api[_-]\?key\s*[:=]\s*['\"][^'\"]*['\"]" Sources/ Tests/ --include="*.swift" 2>/dev/null; then
          echo "::warning::Potential API key pattern found"
        fi
        
        # Tokens (case-insensitive)  
        if grep -ri "token\s*[:=]\s*['\"][^'\"]*['\"]" Sources/ Tests/ --include="*.swift" 2>/dev/null; then
          echo "::warning::Potential token pattern found"
        fi
        
        # Passwords
        if grep -ri "password\s*[:=]\s*['\"][^'\"]*['\"]" Sources/ Tests/ --include="*.swift" 2>/dev/null; then
          echo "::warning::Potential password pattern found"
        fi
        
        echo "Secret scan completed"
        
  documentation:
    name: Documentation Check
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'
        
    - name: Generate Documentation
      run: |
        swift package generate-documentation --warnings-as-errors
        
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main'
      with:
        name: documentation
        path: .build/plugins/Swift-DocC/outputs/XcodeBuildServer.doccarchive
        retention-days: 7