name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  SWIFT_VERSION: '6.1'
  XCODE_VERSION: '16.2'

jobs:
  build-release:
    name: Build Release Binaries
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
  
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ env.SWIFT_VERSION }}

    - name: Verify Swift Version
      run: |
        swift --version
        which swift
    
    - name: Build for macOS (Universal)
      run: |
        swift build -c release --arch arm64 --arch x86_64
        
    - name: Create Release Archive
      run: |
        mkdir -p release
        cp .build/apple/Products/Release/XcodeBuildServerCLI release/XcodeBuildServerCLI
        chmod +x release/XcodeBuildServerCLI
        
        # Create tar.gz
        tar -czf xcode-build-server-macos-universal.tar.gz -C release XcodeBuildServerCLI

        # Create zip
        cd release && zip ../xcode-build-server-macos-universal.zip XcodeBuildServerCLI && cd ..
        
    - name: Generate Checksums
      run: |
        shasum -a 256 xcode-build-server-macos-universal.tar.gz > checksums.txt
        shasum -a 256 xcode-build-server-macos-universal.zip >> checksums.txt
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          xcode-build-server-macos-universal.tar.gz
          xcode-build-server-macos-universal.zip
          checksums.txt
        generate_release_notes: true
        prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
        body: |
          ## Changes in this Release
          
          ### Installation
          
          #### Homebrew (Recommended)
          ```bash
          # Coming soon
          brew install XcodeBuildServerCLI
          ```
          
          #### Manual Installation
          1. Download the appropriate archive for your platform
          2. Extract the binary: `tar -xzf xcode-build-server-macos-universal.tar.gz`
          3. Move to PATH: `mv XcodeBuildServerCLI /usr/local/bin/`
          4. Make executable: `chmod +x /usr/local/bin/XcodeBuildServerCLI`
          
          ### Usage
          ```bash
          XcodeBuildServerCLI --help
          ```
          
          ### Checksums
          Verify your download with the checksums provided in `checksums.txt`.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}